# Generated by Django 4.2.7 on 2024-01-23 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('year', models.IntegerField(verbose_name='year held')),
                ('type', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('session_num', models.IntegerField()),
                ('event_group', models.CharField(max_length=20)),
                ('group_order', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sportsday_site.category')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('colour', models.CharField(help_text="Hex code of the house's colour", max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentid', models.IntegerField(unique=True, verbose_name='student ID')),
                ('firstname', models.CharField(max_length=40, verbose_name='first name')),
                ('lastname', models.CharField(max_length=40, verbose_name='last name')),
                ('tutorgroup', models.CharField(max_length=20, verbose_name='tutor group')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sportsday_site.category')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sportsday_site.house')),
            ],
        ),
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('result1', models.FloatField(blank=True, help_text='Use this for track events', null=True, verbose_name='result 1')),
                ('result1_fail_type', models.CharField(blank=True, help_text='Enter the reason why this result is invalid', max_length=20, null=True, verbose_name='result 1 fail reason')),
                ('result2', models.FloatField(blank=True, null=True, verbose_name='result 2')),
                ('result2_fail_type', models.CharField(blank=True, help_text='Enter the reason why this result is invalid', max_length=20, null=True, verbose_name='result 2 fail reason')),
                ('result3', models.FloatField(blank=True, null=True, verbose_name='result 3')),
                ('result3_fail_type', models.CharField(blank=True, help_text='Enter the reason why this result is invalid', max_length=20, null=True, verbose_name='result 3 fail reason')),
                ('signed_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='sportsday_site.event', verbose_name='event')),
                ('signed_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signups', to='sportsday_site.student', verbose_name='student')),
            ],
            options={
                'unique_together': {('signed_student', 'signed_event')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='sportsday_site.signup'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together={('year', 'session_num', 'event_group', 'group_order')},
        ),
    ]
